docs/docs_source/scenarios/proofkeys.rst
The reason the X-WOPI_TimeStamp header is included in the signed payload
is to ensure that the signature is not stale.  The WOPI Host should
reject the request if the timestamp is older than 20 minutes.  At least that was the case when it was first implemented...
=> Add recency requirement to verification steps

docs/docs_source/concepts.rst, docs/docs_source/contributing/build_docs.rst, docs/docs_source/discovery.rst, docs/docs_source/postmessage.rst, docs/docs_source/wopi/files/PutRelativeFile.rst
Use consistent doc formatting for responses, and clarify that the
response is JSON.
Fixes #65.
=> Clean up PutRelativeFile docs.

docs/docs_source/postmessage.rst
We send a set of common values on every PostMessage request we make,
they should be documented.
=> Add Common Values to PostMessage docs

samples/SampleWopiHandler/SampleWopiHandler/WopiHandler.cs
The length calculation for the substring is invalid
=> Update WopiHandler.cs - malformed Substring

docs/rest/src/bootstrapper/Bootstrap.rst
Changing example providerId to better match our conventions, i.e.
starting with tp_. Also made the example response values match what was
in the preceding table.
=> Change providerId example to tp_contoso

docs/native/src/identity/oauthparams.rst, docs/native/src/identity/sessioncontext.rst, docs/native/src/identity/specifytokenissuance.rst
Filled out page on custom session context, and additional URL
parameters, and made example in token issuance page use same style as
other pages.
=> Additional native auth documentation (session context, url params)

docs/rest/src/_fragments/responses/GetRootContainer (bootstrapper).json
making the hosting url and sharing url non-empty string. 
The previous empty string was making partners think optional values should be "" while they should just be omitted. Adding real values to make it more clear.
=> Update GetRootContainer (bootstrapper).json

docs/online/src/build_test_ship/validator.rst
Include an important note to run the Test/Environment Discovery URL to run the latest version of the WOPI validation application.
=> Adding a Note to use Test/Environment Discovery URL

docs/_shared/spelling_wordlist.txt, docs/online/src/index.rst, docs/online/src/scenarios/customization.rst, docs/online/src/scenarios/postmessage.rst, docs/online/src/scenarios/workflow.rst, docs/rest/src/_fragments/param_types.rst, docs/rest/src/files/CheckFileInfo.rst
This is an initial attempt at adding info on the Workflow-related properties and post messages to the docs.
See #258, which tracks adding more narrative documentation around the workflow-related scenarios.
=> Start adding docs for workflow.

docs/rest/src/concepts.rst, docs/rest/src/containers/CheckContainerInfo.rst, docs/rest/src/containers/GetShareUrl.rst, docs/rest/src/files/CheckFileInfo.rst, docs/rest/src/files/GetShareUrl.rst, docs/rest/src/index.rst
- We're extending the Wopi protocol to support Share URLs.
- I've updated the Key Concepts page with "Share URL" as a new term.
- I've updated CheckFileInfo and CheckContainerInfo with a new property
called SupportedShareUrlTypes.
- I've added two new pages for the GetShareUrl operation for files and
containers.
=> Adding documentation for Sharing

docs/online/src/build_test_ship/settings.rst
This continues to come up when on-boarding new hosts. An example should help illustrate why this requirement exists.
=> Add examples illustrating why dedicated WOPI domains are required

docs/rest/src/files/CheckFileInfo.rst
Add documentation for the new AllowErrorRequestPrompt field on the CheckFileInfoResponse.
When set to true, if a user hits a failure, they can be prompted for additional information.
When set to false, no additional information is collected and no prompt is shown.
=> Add documentation for CheckFileInfoResponse.AllowErrorReportPrompt

docs/online/src/build_test_ship/testing.rst
The validator now tests for unknown CFI properties and correct property types.
=> Remove manual testing steps that are no longer needed

docs/online/src/_fragments/required_validator_tests.rst
The FileVersion tests are easy to address for hosts (add a header to the response for several WOPI operations) and reduce the amount of manual testing that needs to be done during validation.
The PutUserInfo tests are new; hosts that support PutUserInfo must be passing these tests to ensure their implementation is correct.
=> Make the FileVersion and PutUserInfo test groups required for prod

samples/SampleWopiHandler/SampleWopiHandler/WopiHandler.cs, samples/SampleWopiHandler/SampleWopiHandler/WopiRequest.cs, samples/SampleWopiHandler/SampleWopiHandler/WopiResponse.cs
AccessToken, FileVersion, DoubleLock and CheckFileInfoSchema test groups were failing for WopiCore.
=> Fix sample wopi handler to pass all WopiCore Validation tests

docs/rest/src/files/CheckFileInfo.rst
An array of strings named CobaltCapabilities can be returned in the response of CheckFileInfo. Add this to the document
=> Add CobaltCapabilities to CheckFileInfo

docs/rest/src/files/CheckFileInfo.rst
Today a WOPI host experiencing capacity stress doesn't have a mechanism for telling a WOPI client that they are under heavy load.  They also don't have a way to help the WOPI client prioritize which of its sessions should be throttled.  Add two new fields to the CheckFileInfo response.
ClientThrottlingProtection: This is used for the WOPI host to tell the WOPI client how to prioritize which users/documents should be throttled when the WOPI client is experiencing heavy load.
RequestedCallThrottling: This is used for the WOPI host to tell the WOPI client that the host is currently experiencing heavy load and would like the current document/user/session to have a degraded (throttled) experience.  This will reduce host load and allow the WOPI host to recover.
=> Add CheckFile APIs for Throttling

docs/native/src/index.rst, docs/native/src/overview.rst, docs/online/src/index.rst, docs/online/src/overview.rst
The Cloud Storage Partner Program links in the WOPI documentation have not been updated to their new location at Microsoft.com, and still point to their legacy location on Office.com.
=> Fix CSPP link in WOPI documentation.

docs/rest/src/files/CheckFileInfo.rst
Add SharingStatus Documentation for the new property being added to CheckFileInfo. SharingStatus is a new property that will allow you to understand if users other than the document owner have access to the file.
=> Add SharingStatus Documentation

docs/online/src/tables/file_sizes.csv
We've increased our limit and therefore the documentation should be updated.
=> Update Word Web's FileSizeLimit from 50 to 100 MB

docs/_shared/rst_prolog.rst, docs/native/src/onboarding/onboarding.rst
Add link to the CSPP Yammer Group in the onboarding page, so that folks know where they can go to provide the needed information to Microsoft.
=> Update information on the onboarding page

docs/rest/src/files/CheckFileInfo.rst
RequestedCallThrottling and ClientThrottlingProtection have shipped so remove the prerelease flag from the CheckFileInfo API's documentation.
=> Remove prerelease flag from shipped properties

docs/online/src/scenarios/postmessage.rst
Updating the post message documentation with the two new post messages: App_IsFrameTrusted and Host_IsFrameTrusted.
The App_IsFrameTrusted message is posted by wac application frame to initiate handshake flow.
The host is expected to check whether the top frame is trusted and post Host_IsFrameTrusted message back to wac application.
=> Updated post message documentation to include IsFrameTrusted messages.
